/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2024-10-15 07:06:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class welcome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Welcome to ReelVibe</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: Arial, sans-serif;\r\n");
      out.write("            background-color: #1c1c1c;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            line-height: 1.6;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            overflow-x: hidden;\r\n");
      out.write("        }\r\n");
      out.write("        .welcome_nav {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: space-between;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            padding: 20px 5%;\r\n");
      out.write("            background-color: #2c2c2c;\r\n");
      out.write("        }\r\n");
      out.write("        .welcome_nav h1 {\r\n");
      out.write("            font-size: 28px;\r\n");
      out.write("            color: #ff6f61;\r\n");
      out.write("        }\r\n");
      out.write("        .welcome_nav_list {\r\n");
      out.write("            list-style: none;\r\n");
      out.write("            display: flex;\r\n");
      out.write("        }\r\n");
      out.write("        .welcome_nav_list li {\r\n");
      out.write("            margin-left: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        .welcome_nav_list a {\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("        }\r\n");
      out.write("        .welcome_nav_list a:hover {\r\n");
      out.write("            color: #ff6f61;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Slideshow container */\r\n");
      out.write("        .slideshow-container {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            height: 100vh;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Each slide */\r\n");
      out.write("        .mySlides {\r\n");
      out.write("            display: none;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            opacity: 0; /* Initially hidden */\r\n");
      out.write("            transition: opacity 1.5s ease-in-out; /* Smooth transition for fade effect */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Background images with darker effect */\r\n");
      out.write("        .mySlides img {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            object-fit: cover;\r\n");
      out.write("            filter: brightness(40%); /* Darken the images */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .welcome_content {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            right: 0;\r\n");
      out.write("            bottom: 0;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            padding: 50px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .welcome_content h2 {\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("            font-size: 48px;\r\n");
      out.write("            color: #ff6f61;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .welcome_content p {\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .welcome_buttons {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            gap: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .welcome_buttons a {\r\n");
      out.write("            background-color: #ff6f61;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            transition: background-color 0.3s ease-in-out;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .welcome_buttons a:hover {\r\n");
      out.write("            background-color: #e65c50;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        footer {\r\n");
      out.write("            background-color: #2c2c2c;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding: 20px 0;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            margin-top: auto;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .social_links {\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .social_links a {\r\n");
      out.write("            color: #ff6f61;\r\n");
      out.write("            margin: 0 10px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-size: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Media Queries for Responsiveness */\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .welcome_content h2 {\r\n");
      out.write("                font-size: 36px;\r\n");
      out.write("            }\r\n");
      out.write("            .welcome_nav h1 {\r\n");
      out.write("                font-size: 24px;\r\n");
      out.write("            }\r\n");
      out.write("            .welcome_nav_list {\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("                align-items: flex-start;\r\n");
      out.write("            }\r\n");
      out.write("            .welcome_nav_list li {\r\n");
      out.write("                margin-left: 0;\r\n");
      out.write("                margin-top: 10px;\r\n");
      out.write("            }\r\n");
      out.write("            .welcome_buttons {\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 480px) {\r\n");
      out.write("            .welcome_content h2 {\r\n");
      out.write("                font-size: 28px;\r\n");
      out.write("            }\r\n");
      out.write("            .welcome_content p {\r\n");
      out.write("                font-size: 16px;\r\n");
      out.write("            }\r\n");
      out.write("            .welcome_buttons a {\r\n");
      out.write("                padding: 8px 16px;\r\n");
      out.write("                font-size: 14px;\r\n");
      out.write("            }\r\n");
      out.write("            .welcome_nav_list li {\r\n");
      out.write("                margin-top: 15px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Fade animation for the slides */\r\n");
      out.write("        .fade {\r\n");
      out.write("            animation: fadeIn 2s ease-in-out forwards; /* Fades in each slide */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Animation keyframes */\r\n");
      out.write("        @keyframes fadeIn {\r\n");
      out.write("            from { opacity: 0; }\r\n");
      out.write("            to { opacity: 1; }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <nav class=\"welcome_nav\">\r\n");
      out.write("        <h1>ReelVibe</h1>\r\n");
      out.write("        <ul class=\"welcome_nav_list\">\r\n");
      out.write("            <li><a href=\"faq.jsp\">FAQ</a></li>\r\n");
      out.write("            <li><a href=\"about.jsp\">About Us</a></li>\r\n");
      out.write("            <li><a href=\"contact.jsp\">Contact</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("    <!-- Slideshow Container -->\r\n");
      out.write("    <div class=\"slideshow-container\">\r\n");
      out.write("        <div class=\"mySlides fade\">\r\n");
      out.write("            <img src=\"image/im6.jpg\" alt=\"Movie background 1\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"mySlides fade\">\r\n");
      out.write("            <img src=\"image/im2.jpg\" alt=\"Movie background 2\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"mySlides fade\">\r\n");
      out.write("            <img src=\"image/im3.jpg\" alt=\"Movie background 3\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"mySlides fade\">\r\n");
      out.write("            <img src=\"image/im4.jpg\" alt=\"Movie background 4\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"mySlides fade\">\r\n");
      out.write("            <img src=\"image/im5.jpg\" alt=\"Movie background 5\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Welcome content -->\r\n");
      out.write("        <div class=\"welcome_content\">\r\n");
      out.write("            <h2>Welcome to ReelVibe</h2>\r\n");
      out.write("            <p>Your ultimate destination for browsing movies and TV series. Discover trending titles, top-rated content, and explore by genres. Join us and dive into the world of entertainment!</p>\r\n");
      out.write("            <div class=\"welcome_buttons\">\r\n");
      out.write("                <a href=\"login.jsp\">Login</a>\r\n");
      out.write("                <a href=\"register.jsp\">Register</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("        <p>© 2024 ReelVibe - Your Movie & TV Series Destination</p>\r\n");
      out.write("        <div class=\"social_links\">\r\n");
      out.write("            <a href=\"https://www.facebook.com\" target=\"_blank\">Facebook</a>\r\n");
      out.write("            <a href=\"https://www.twitter.com\" target=\"_blank\">Twitter</a>\r\n");
      out.write("            <a href=\"https://www.instagram.com\" target=\"_blank\">Instagram</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        let slideIndex = 0;\r\n");
      out.write("        showSlides();\r\n");
      out.write("\r\n");
      out.write("        function showSlides() {\r\n");
      out.write("            let slides = document.getElementsByClassName(\"mySlides\");\r\n");
      out.write("            for (let i = 0; i < slides.length; i++) {\r\n");
      out.write("                slides[i].style.display = \"none\";  // Hide all slides\r\n");
      out.write("                slides[i].style.opacity = 0;       // Set opacity to 0 (hidden)\r\n");
      out.write("            }\r\n");
      out.write("            slideIndex++;\r\n");
      out.write("            if (slideIndex > slides.length) { slideIndex = 1; }\r\n");
      out.write("            slides[slideIndex-1].style.display = \"block\";   // Show current slide\r\n");
      out.write("            slides[slideIndex-1].style.opacity = 1;         // Fade in current slide\r\n");
      out.write("            setTimeout(showSlides, 3000); // Change image every 3 seconds\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
